version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - 9200:9200
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
      xpack.security.enrollment.enabled: 'true'
      ELASTIC_PASSWORD: 'elastic'
      ELASTIC_USERNAME: 'elastic_user'
  kibana:
    image: kibana:8.8.0
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601