version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:8.8.0
    deploy:
      resources:
        limits:
          memory: 2g
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
      xpack.security.enrollment.enabled: 'true'
      ELASTIC_PASSWORD: 'elastic'
      ELASTIC_USERNAME: 'elastic_user'

  kibana:
    image: kibana:8.8.0
    deploy:
      resources:
        limits:
          memory: 1g
    volumes:
      - ./elastic/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601

  eureka-server:
    image: eureka.jar:latest
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - 8761:8761

  api-gateway:
    image: api-gateway.jar:latest
    deploy:
      resources:
        limits:
          memory: 1g
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 8765:8765


  db:
    #    image: mysql:5.7
    image: mysql:8.0.32
    environment:
      MYSQL_DATABASE: 'stud_projects'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306


  elastic-service:
    build: ./elastic-app.jar
    restart: on-failure
    image: elastic-app.jar:latest
    deploy:
      resources:
        limits:
          memory: 2g
      replicas: 2
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - elasticsearch
      - eureka-server
    ports:
      - 8082-8086:8082

  main_app:
    build: ./app.jar
    restart: on-failure
    image: app.jar:latest
    deploy:
      resources:
        limits:
          memory: 1g
    depends_on:
      - db
      - elastic-service
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 8080:8080

volumes:
  dbdata:
